version: '3'
services:
  #  consul:
  #    image: "consul:0.8.0"
  #    ports:
  #    - "8500:8500"

  gateway-mirror:
    image: menya84/gateway-mirror
    tty: true
    stdin_open: true
    ports:
    #      - 9990 # Admin
    #      - 4141:4141 # Outgoing
    - "8070:8070"
  #    - "9990:9990"

  user-service:
    image: menya84/user-service
    tty: true
    stdin_open: true
    ports:
  #      - 4140:4140 # Incoming
  #      - 4141:4140 # Outgoing
  #      - 9990 # Admin
        - "8071:8071"
  #      - "9990:9990"

  order-service:
    image: menya84/order-service
    tty: true
    stdin_open: true
    ports:
    #      - 4140:4140 # Incoming
    #      - 4141:4141 # Outgoing
    #      - 9990 # Admin
    - "8072:8072"
  #      - "9990:9990"

  consul-server:
    image: gliderlabs/consul-server
    command: ["-bootstrap"]
    ports:
    - "8500:8500"

  consul-registrator:
    image: gliderlabs/registrator
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    command: ["consul://consul-server:8500"]
    depends_on:
      - consul-server

  linkerd:
    image: buoyantio/linkerd:1.6.0
    ports:
    - "4140:4140"
    - "4141:4141"
    - "9990:9990"
    # we must mount the config file and the disco directory
    volumes:
    - ./linkerd.yaml:/io.buoyant/linkerd.yaml:ro
    command: >
      /io.buoyant/linkerd.yaml