admin:
  ip: 0.0.0.0
  port: 9990

usage:
  enabled: false

telemetry:
  - kind: io.l5d.zipkin
    host: zipkin
    port: 9410
    sampleRate: 1.0

  - kind: io.l5d.prometheus
  - kind: io.l5d.recentRequests
    sampleRate: 1

namers:
  - kind: io.l5d.fs
    rootDir: /disco
  - kind: io.l5d.consul
    experimental: true
    host: consul-server
    port: 8500
    includeTag: false
    setHost: false

routers:
  - protocol: http
    #  announcers:
    #  - kind: io.l5d.serversets
    #    zkAddrs:
    #    - host: zookeeper
    #      port: 2181
    #    pathPrefix: /discovery/prod
    label: http
    httpAccessLog: access.log
    httpAccessLogRollPolicy: daily
    httpAccessLogAppend: true
    httpAccessLogRotateCount: -1
    identifier:
      kind: io.l5d.methodAndHost
    #    httpUriInDst: true
    tracePropagator:
      kind: io.l5d.zipkin
    dstPrefix: /http
    servers:
      - port: 4141
        ip: 0.0.0.0
    #    announce:
    #    - /#/io.l5d.serversets/user-service
    #    - /#/io.l5d.serversets/order-service
    # Route outgoing traffic based on the Host header
    dtab: |
      /srv         => /io.l5d.fs ;
      /srv => /#/io.l5d.consul/dc1;
      /host        => /srv ;
      /http/1.1/*  => /host ;
    service:
      kind: io.l5d.static
      configs:
        - prefix: /http/1.1/GET
          totalTimeoutMs: 10000
          responseClassifier:
            kind: io.l5d.http.retryableRead5XX
          retries:
            budget:
              minRetriesPerSec: 1
            backoff:
              kind: constant
              ms: 100

        - prefix: /http/1.1/GET/order-service
          totalTimeoutMs: 4000
          retries:
            budget:
              minRetriesPerSec: 0
              percentCanRetry: 2.0
            #          ttlSecs: 15
          #        backoff:
          #          kind: jittered
          #          minMs: 10
          #          maxMs: 10000
          responseClassifier:
            kind: io.l5d.http.retryableRead5XX

        - prefix: /http/1.1/GET/user-service
          responseClassifier:
            kind: io.l5d.http.nonRetryable5XX
          totalTimeoutMs: 2000

    client:
      kind: io.l5d.static
      configs:
        - prefix: /#/io.l5d.consul/dc1
          # The timeout for a single request attempt on the client.  If this
          # timeout is reached, the request attempt will be canceled and the request
          # will be retried if there is still time remaining in the total timeout.
          requestAttemptTimeoutMs: 200
          loadBalancer:
            kind: roundRobin
          failureAccrual:
            kind: io.l5d.consecutiveFailures
            failures: 10
            backoff:
              kind: constant
              ms: 1000
        - prefix: /#/io.l5d.consul/dc1/order-service
          failureAccrual:
            kind: io.l5d.consecutiveFailures
            failures: 3

        - prefix: /#/io.l5d.consul/dc1/user-service
          failureAccrual:
            kind: io.l5d.consecutiveFailures
            failures: 1
