global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'linkerd'
    metrics_path: /admin/metrics/prometheus
    static_configs:
      - targets:
          - 'linkerd:9990'
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'api-gateway:8070'
  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'user-service:8071'
  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'order-service:8072'